### ISSUE TITLE
Cross-browser fix in history's checkUrl

### ISSUE THREAD

**Issue by sadasant** [BlueSpire/Durandal-Bower#7]
Hi! As [this PR](https://github.com/BlueSpire/Durandal/pull/700) was merged to Durandal recently, I wonder if the changes could be built into this repo, as this is the one that we can install using `npm`.

Please! 🙇 🙏

**Comment by sadasant** [comment]
@EisenbergEffect Hi! Sorry for asking, but is there a schedule for a new release/minor version that could contain this fix?

**Comment by daedalus28** [comment]
@EisenbergEffect This was affecting us as well - it was great to have this merged but until the npm module is updated it doesn't help

**Comment by frozegnome** [comment]
@EisenbergEffect I second the above, we're waiting for this to be available on npm before we move forward

**Comment by EisenbergEffect** [comment]
Unfortunately, there won't be a release of Durandal in the short-term. Fortunately, npm can install directly from GitHub. That's a common practice for leveraging pre-release builds or patch fixes. That would be my recommended approach for now.
